site_name: HTTPX-CACHE
site_description: Simple caching transport for httpx.
site_url: https://obendidi.github.io/httpx-cache/

repo_name: obendidi/httpx-cache
repo_url: https://github.com/obendidi/httpx-cache
edit_uri: ""

theme:
  name: "material"

nav:
  - Introduction: "index.md"
  - User Guide: "guide.md"
  - Cache Control: "cache_control.md"
  - Developper Interface: "api.md"

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences

extra_css:
  - css/custom.css
